import { makeStyles } from 'tss-react/mui';

export const useStyles = makeStyles()((theme) => ({
  root: {
    display: 'flex',
    width: '100%',
    height: 80,
    overflow: 'hidden',
    borderRadius: 0,
    boxShadow: '0px 4px 4px rgba(239, 239, 239, 0.25), 0px 2px 5px #EFEFEF',
    filter: 'none',
  },
  logoBackground: {
    display: 'flex',
    width: 500,
    height: 80,
    background: `radial-gradient(circle, rgba(230,0,0,1) 0%, rgba(179,47,102,1) 51%, rgba(130,93,199,1) 100%)`,
    filter: `blur(25px)`,
    borderRadius: '0px 0px 50px 0px',
    position: 'absolute',
    top: 0,
    left: 0,
    transform: 'translateX(-50%)',
    opacity: 1,
    '&:before': {
      content: '""',
      display: 'block',
      width: '100%',
      height: '100%',
      position: 'absolute',
      top: 0,
      left: 0,
      transform: 'translateX(-50%)',
      background: `radial-gradient(circle, rgba(230,0,0,1) 0%, rgba(179,47,102,1) 51%, rgba(130,93,199,1) 100%)`,
      filter: `blur(25px)`,
      borderRadius: '0px 0px 50px 0px',
      zIndex: 1,
    },
  },
  logo: {
    width: 148,
    height: 32,
    position: 'relative',
    zIndex: 2,
  },
  container: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    boxSizing: 'border-box',
  },
  actions: {
    display: 'flex',
    gap: '1.5rem',
    alignItems: 'center',
  },
  activeAccount: {
    display: 'block',
    position: 'relative',
    cursor: 'pointer',
    '&:after': {
      content: '""',
      display: 'block',
      width: '100%',
      height: '2px',
      position: 'absolute',
      bottom: '-3px',
      left: 0,
      backgroundColor: theme.palette.primary.main,
    },
  },
}));
