export const enum AdminAuth {
  CREATE_SYSTEM = 'CREATE_SYSTEM',
  EDIT_SYSTEM = 'EDIT_SYSTEM',
  DELETE_SYSTEM = 'DELETE_SYSTEM',
  READ_SYSTEM_AUTH = 'READ_SYSTEM_AUTH',
  ASSIGN_SYSTEM_ADMIN = 'ASSIGN_SYSTEM_ADMIN',
  DELETE_SYSTEM_ADMIN = 'DELETE_SYSTEM_ADMIN',
  READ_SYSTEM_ADMIN = 'READ_SYSTEM_ADMIN',
}

export const enum PortalAuth {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}
