export enum QueryCacheKey {
  'SYSTEM_LIST' = 'SYSTEM_LIST',
  'SYSTEM_DATA' = 'SYSTEM_DATA',
  'ACTION_HISTORY_SUMMARY' = 'ACTION_HISTORY_SUMMARY',
  'ACTION_HISTORY_LIST' = 'ACTION_HISTORY_LIST',
  'CREATE_SYSTEM' = 'CREATE_SYSTEM',
  'UPDATE_SYSTEM' = 'UPDATE_SYSTEM',
  'DELETE_SYSTEM' = 'DELETE_SYSTEM',
}
