import { ActionStatus, IndividualActionHistory } from '@sso-platform/types';
import { BaseData } from './db';

export type ActionHistoryData = IndividualActionHistory & BaseData;
export const generateActionHistoryData = (): ActionHistoryData[] => {
  return [
    {
      id: '1',
      actionHistoryId: '1',
      platform: 'SSO單一登入平台',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登出SSO',
      authFunctionCode: 'logout',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 19:32:49',
    },
    {
      id: '2',
      actionHistoryId: '2',
      platform: '會員管理系統',
      authFunctionCategory: '系統',
      authFunctionName: '編輯會員所有資訊',
      authFunctionCode: 'edit_member',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 09:36:56',
    },
    {
      id: '3',
      actionHistoryId: '3',
      platform: '會員管理系統',
      authFunctionCategory: '系統',
      authFunctionName: '新建新的會員',
      authFunctionCode: 'create_new_member',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 09:04:13',
    },
    {
      id: '4',
      actionHistoryId: '4',
      platform: '會員管理系統',
      authFunctionCategory: '系統',
      authFunctionName: '新建新的的會員',
      authFunctionCode: 'create_new_member',
      actionStatus: ActionStatus.FAIL,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.04 19:32:49',
    },
    {
      id: '5',
      actionHistoryId: '5',
      platform: '會員管理系統',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登入',
      authFunctionCode: 'login',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.04 09:03:12',
    },
    {
      id: '6',
      actionHistoryId: '6',
      platform: 'SSO單一登入平台',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登入SSO',
      authFunctionCode: 'login',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 19:32:49',
    },
    {
      id: '7',
      actionHistoryId: '7',
      platform: 'SSO單一登入平台',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登出SSO',
      authFunctionCode: 'logout',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 09:36:56',
    },
    {
      id: '8',
      actionHistoryId: '8',
      platform: 'AP0 Admin Panel',
      authFunctionCategory: '系統',
      authFunctionName: '編輯子系統',
      authFunctionCode: 'update_system',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 09:04:13',
    },
    {
      id: '9',
      actionHistoryId: '9',
      platform: 'AP0 Admin Panel',
      authFunctionCategory: '系統',
      authFunctionName: '建立子系統',
      authFunctionCode: 'create_system',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.04 19:32:49',
    },
    {
      id: '10',
      actionHistoryId: '10',
      platform: 'AP0 Admin Panel',
      authFunctionCategory: '系統',
      authFunctionName: '建立子系統',
      authFunctionCode: 'create_system',
      actionStatus: ActionStatus.FAIL,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.04 09:03:12',
    },
    {
      id: '11',
      actionHistoryId: '11',
      platform: 'AP0 Admin Panel',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登入',
      authFunctionCode: 'login',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 19:32:49',
    },
    {
      id: '12',
      actionHistoryId: '12',
      platform: 'SSO單一登入平台',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登出SSO',
      authFunctionCode: 'logout',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 09:36:56',
    },
    {
      id: '13',
      actionHistoryId: '13',
      platform: 'AP0 Admin Panel',
      authFunctionCategory: '系統',
      authFunctionName: '編輯子系統',
      authFunctionCode: 'update_system',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.05 09:04:13',
    },
    {
      id: '14',
      actionHistoryId: '14',
      platform: 'AP0 Admin Panel',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登入',
      authFunctionCode: 'login',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.04 19:32:49',
    },
    {
      id: '15',
      actionHistoryId: '15',
      platform: 'SSO單一登入平台',
      authFunctionCategory: '登入/登出',
      authFunctionName: '登入SSO',
      authFunctionCode: 'login',
      actionStatus: ActionStatus.SUCCESS,
      actionIp: '1.34.222.199',
      actionDate: '2022.11.04 09:03:12',
    },
  ];
};
